# TODO: once ginga is in the astropy affiliated package format we should
# switch to the package-template .travis.yml file and change the tests
# to run like this:
# python setup.py test
# python setup.py build_sphinx

language: python

python:
  - 2.7
  - 3.4

env:
  - ASTROPY_VERSION=stable
  - ASTROPY_VERSION=development

before_install:
  # Check if we are running Python 2 or 3. This is needed for the apt-get package names
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export P="3"; fi

  - export PYTHONIOENCODING=UTF8 # just in case

  # Use system python, not virtualenv, because building the dependencies from source takes too long
  - deactivate # the virtualenv

install:
  # Get most of the required dependencies via apt-get
  - sudo apt-get update -qq
  #libatlas-dev liblapack-dev gfortran
  - sudo apt-get install -qq python${P} python${P}-numpy python${P}-scipy
  # for installation and tests
  - sudo apt-get install -qq python${P}-setuptools python${P}-nose
  # for building sphinx doc
  - sudo apt-get install -qq python${P}-sphinx

  # Note: cython3 will only appear in Ubuntu 13.04: cython${P}
  # So for now we install it from source
  - curl -L https://pypi.python.org/packages/source/C/Cython/Cython-0.18.tar.gz > Cython-0.18.tar.gz
  - tar zxf Cython-0.18.tar.gz
  - cd Cython-0.18
  - sudo python${P} setup.py install
  - cd ..

  # GTK is not available for Python 3, so we test QT/pyside only for now ...
  # python${PYTHON_SUFFIX}-gtk2
  - sudo apt-get install -qq python${P}-pyside

  # No apt-get install python3-pip before Ubuntu 13.04 ... python${P}-pip 
  #- if [[ $ASTROPY_VERSION == stable ]]; then sudo pip${P} -q install astropy --use-mirrors; fi
  #- if [[ $ASTROPY_VERSION == development ]]; then sudo pip${P} -q install git+http://github.com/astropy/astropy.git#egg=astropy --use-mirrors; fi

  # ... so for now use setup.py to install astropy
  - git clone git://github.com/astropy/astropy.git
  - cd astropy
  - if [[ $ASTROPY_VERSION == stable ]]; then git checkout v0.4.1; fi
  - sudo python${P} setup.py install
  - cd ..

script:
  # Install ginga
  - sudo python${P} setup.py install

  - python${P} -c 'import ginga'
  - which ginga

  # run unit tests
  # this doesn't seem to work:
  # - python${P} setup.py test
  - sudo python${P} setup.py build
  - nosetests${P} build/lib*/ginga/tests

  # build documentation
  # there is a problem with this presently
  #- python${P} setup.py build_sphinx

